# Netlify configuration for GanttLab monorepo

[build]
  # Run everything from the repo root so the root package.json scripts are available
  base = "."
  # Builds the Vue webapp located in packages/ganttlab-adapter-webapp
  command = "npm run build:webapp"
  # Directory to publish (the Vue CLI dist folder)
  publish = "packages/ganttlab-adapter-webapp/dist"

[build.environment]
  # If you upgrade to Node 18+ and encounter OpenSSL issues, this keeps builds working
  NODE_OPTIONS = "--openssl-legacy-provider"
  # Ensure NPM installs even when peer-dependency conflicts arise (this project needs it)
  NPM_FLAGS = "--legacy-peer-deps"

# Handle client-side routing for the SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 